### ISSUE TITLE
What am I doing wrong? statusCode:404

### ISSUE THREAD

**Issue by kostrykin** [hfreire/browser-as-a-service#130]
After running

```bash
docker run -d -p "9453:3000" hfreire/browser-as-a-service
```

and then opening `http://localhost:9453/` in my web browser I get:

```json
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

What does that mean? I'm on Ubuntu 14.04.

**Comment by hfreire** [comment]
Hi!

In 2a4932d12694dccace63c45d31bd9fafae4231c4  I've updated the README.md file with:
- an example of how to browse a website through the REST API 
- instructions on how to access the REST API documentation in
